n1=int(input("enter any number"))
n2=int(input("enter any number"))
n3=int(input("enter any number"))
n4=int(input("enter any number"))
n5=int(input("enter any number"))
n6=int(input("enter any number"))
n7=int(input("enter any number"))
list1=[n1,n2,n3,n4,n5,n6,n7]
list2=set(list1)
list3=sorted(list2)
print(list(list3))
